if not game:IsLoaded() then game.Loaded:Wait() end
script_key = "ZPNjramxnntTdIsyQVTYhmIfHfaLEAOu";
getgenv().UserConfig = {
	["Auto Double Or Nothing"] = false,
    ["Double Or Nothing Target Wins"] = 1,
    ["FPS Cap"] = 5,
    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Limit Plant Seed"] = {
        ["Maple Carrot"] = 50,
        ["Maple Tulip"] = 50,
        ["Maple Bamboo"] = 50,
        ["Maple Mushroom"] = 100,
    },
    ["Limit Buy Seed"] = {
        -- Single Harvest
        ["Maple Carrot"] = 9999,
        ["Maple Tulip"] = 9999,
        ["Maple Bamboo"] = 9999,
        ["Maple Mushroom"] = 9999,
        -- Multi Harvest
        ["Atlantic Giant Pumpkin"] = 9999,
        ["Amber Cranberry"] = 9999,
        ["Maple Dragon Fruit"] = 1,
        ["Maple Acorn"] = 3,
        ["Maple Cherry"] = 1,
        ["Maple Sunflower"] = 1,
        ["Maple Venus Fly Trap"] = 1,
        ["Maple Pomegranate"] = 1,
        ["Maple Poison Apple"] = 1,
        ["Maple Venom Spitter"] = 1,
        ["Conifer Cone"] = 1,
    },
	["Harvest Mutation Only"] = {
        ["Atlantic Giant Pumpkin"] = {Multiplier = 2.0},
		["Maple Mushroom"] = {Mutation = true, Multiplier = 1.15, Mode = "All"},
        ["Maple Dragon Fruit"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Acorn"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Cherry"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Sunflower"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Venus Fly Trap"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Pomegranate"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Poison Apple"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Maple Venom Spitter"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Conifer Cone"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
        ["Amber Cranberry"] = {Mutation = true, Multiplier = 2.0, Mode = "All"},
	},
    ["Auction"] = {
		["Min Sheckles"] = "500m",
		["Maple Cherry"] = {["Max Price"] = "2m"},
        ["Maple Sunflower"] = {["Max Price"] = "5m"},
        ["Maple Venus Fly Trap"] = {["Max Price"] = "7m"},
        ["Maple Pomegranate"] = {["Max Price"] = "12m"},
        ["Maple Poison Apple"] = {["Max Price"] = "25m"},
        ["Maple Venom Spitter"] = {["Max Price"] = "30m"},
        ["Conifer Cone"] = {["Max Price"] = "40m"},
        ["Amber Cranberry"] = {["Max Price"] = "140m"},
        ["Atlantic Giant Pumpkin"] = {["Max Price"] = "1m"},
        ["Super Syrup Sprinkler"] = {["Max Price"] = "10m"},
        ["Super Syrup Watering Can"] = {["Max Price"] = "10m"},
        ["Shadow Dragon"] = {["Max Price"] = "100m"},
	},
    ["Favorite"] = {},
    ["Buy Pets"] = {
        ["Turkey"] = {Normal = 6, Big = 6, Huge = 6, Rainbow = 6},
        ["Swan"] = {Normal = 6, Big = 6, Huge = 6, Rainbow = 6},
        ["Wolf"] = {Normal = 6, Big = 6, Huge = 6, Rainbow = 6},
        ["Shadow Dragon"] = 999,
    },
    ["Equip Wolf At Night"] = true,
	["Equip Pets"] = { -- Khong can ghi Wolf vao day nhe
		{"Swan", 6, 1},
		{"Turkey", 6, 2},
	},
	["Sell Pets"] = {},
    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3,
    ["Unlock Pet Slots"] = 6,
    ["Auto Collect Seed Packs"] = true,
    ["Merge Eclipse Bloom"] = true,
    ["Gears"] = {
        ["Buy Gear"] = {
			["Trowel"] = 50,
            ["Harp"] = 100,
            ["Syrup Watering Can"] = 50,
            ["Syrup Sprinkler"] = 50,
            ["Super Syrup Watering Can"] = 50,
            ["Super Syrup Sprinkler"] = 50,
        },
        ["Gears To Use"] = {
            "Trowel",
            "Syrup Watering Can",
			"Syrup Sprinkler",
        ["Harp"] = {["Min Sheckles"] = "30m"},
        },
    },
	-- WH Pet
    ["Webhook Pet URL"] = "https://discord.com/api/webhooks/1534920378466435233/WzrWvxPNXF6cnrtdYNjbB4x12IqiSCdb3SJnBG-nXMDkes2fmaB9e0TAx23ak89jm8XH",
    ["Webhook Pet Name"] = 
